# Copyright © 2025, MIT License, Author: Iwan van der Kleijn
# Hob: A private AI-augmented workspace for project notes and files.

[system]
database-url = "sqlite+aiosqlite:///./hob-data.db"
ai-provider = "openai"

[openai]
api-key="FILL YOUR API KEY HERE"
model = "gpt4o"

