[tool.poetry]
name = "hob"
version = "0.1.0"
description = "Hob: A private AI-augmented workspace for project notes and files"
authors = ["Iwan van der Kleijn <iwanvanderkleijn@gmail.com>"]
readme = "README.md"
license = "MIT"
packages = [
    { include = "app", from = "src" },
    { include = "hob", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.6"
uvicorn = {extras = ["standard"], version = "^0.34.0"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
requests = "^2.32.3"
loguru = "^0.7.3"
pydantic = {extras = ["email"], version = "^2.10.4"}
python-multipart = "^0.0.20"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.36"}
aiosqlite = "^0.20.0"
argon2-cffi = "^23.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
mypy = "^1.14.0"
flake8 = "^7.1.1"
black = "^24.10.0"
ruff = "^0.8.4"
pytest-asyncio = "^0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
check-all = "hob.run_checks:run_checks"

